import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Provider from "./provider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Medical Voice Agent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

   
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/favicon.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
        {children}
        <Toaster/>

        <footer className="w-full text-center py-4 text-sm font-medium text-gray-700 dark:text-gray-200 border-t border-neutral-200 dark:border-neutral-800 mt-10 flex flex-col items-center gap-1">
          <span>
            Made with <span className="text-red-500">♥</span> by <span className="font-semibold">Sachin Dev</span>
          </span>
        </footer>

        </Provider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
